
#line 3 "lex.grib_yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define grib_yyconst const
#else
#define grib_yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (grib_yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((grib_yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE grib_yyrestart(grib_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(grib_yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct grib_yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int grib_yyleng;

extern FILE *grib_yyin, *grib_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define grib_yyless(n) \
	do \
		{ \
		/* Undo effects of setting up grib_yytext. */ \
        int grib_yyless_macro_arg = (n); \
        YY_LESS_LINENO(grib_yyless_macro_arg);\
		*grib_yy_cp = (grib_yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(grib_yy_c_buf_p) = grib_yy_cp = grib_yy_bp + grib_yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up grib_yytext again */ \
		} \
	while ( 0 )

#define unput(c) grib_yyunput( c, (grib_yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t grib_yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct grib_yy_buffer_state
	{
	FILE *grib_yy_input_file;

	char *grib_yy_ch_buf;		/* input buffer */
	char *grib_yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	grib_yy_size_t grib_yy_buf_size;

	/* Number of characters read into grib_yy_ch_buf, not including EOB
	 * characters.
	 */
	int grib_yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int grib_yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int grib_yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int grib_yy_at_bol;

    int grib_yy_bs_lineno; /**< The line count. */
    int grib_yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int grib_yy_fill_buffer;

	int grib_yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via grib_yyrestart()), so that the user can continue scanning by
	 * just pointing grib_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t grib_yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t grib_yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * grib_yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (grib_yy_buffer_stack) \
                          ? (grib_yy_buffer_stack)[(grib_yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (grib_yy_buffer_stack)[(grib_yy_buffer_stack_top)]

/* grib_yy_hold_char holds the character lost when grib_yytext is formed. */
static char grib_yy_hold_char;
static int grib_yy_n_chars;		/* number of characters read into grib_yy_ch_buf */
int grib_yyleng;

/* Points to current character in buffer. */
static char *grib_yy_c_buf_p = (char *) 0;
static int grib_yy_init = 0;		/* whether we need to initialize */
static int grib_yy_start = 0;	/* start state number */

/* Flag which is used to allow grib_yywrap()'s to do buffer switches
 * instead of setting up a fresh grib_yyin.  A bit of a hack ...
 */
static int grib_yy_did_buffer_switch_on_eof;

void grib_yyrestart (FILE *input_file  );
void grib_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE grib_yy_create_buffer (FILE *file,int size  );
void grib_yy_delete_buffer (YY_BUFFER_STATE b  );
void grib_yy_flush_buffer (YY_BUFFER_STATE b  );
void grib_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void grib_yypop_buffer_state (void );

static void grib_yyensure_buffer_stack (void );
static void grib_yy_load_buffer_state (void );
static void grib_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER grib_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE grib_yy_scan_buffer (char *base,grib_yy_size_t size  );
YY_BUFFER_STATE grib_yy_scan_string (grib_yyconst char *grib_yy_str  );
YY_BUFFER_STATE grib_yy_scan_bytes (grib_yyconst char *bytes,int len  );

void *grib_yyalloc (grib_yy_size_t  );
void *grib_yyrealloc (void *,grib_yy_size_t  );
void grib_yyfree (void *  );

#define grib_yy_new_buffer grib_yy_create_buffer

#define grib_yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        grib_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            grib_yy_create_buffer(grib_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->grib_yy_is_interactive = is_interactive; \
	}

#define grib_yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        grib_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            grib_yy_create_buffer(grib_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->grib_yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->grib_yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *grib_yyin = (FILE *) 0, *grib_yyout = (FILE *) 0;

typedef int grib_yy_state_type;

extern int grib_yylineno;

int grib_yylineno = 1;

extern char *grib_yytext;
#define grib_yytext_ptr grib_yytext

static grib_yy_state_type grib_yy_get_previous_state (void );
static grib_yy_state_type grib_yy_try_NUL_trans (grib_yy_state_type current_state  );
static int grib_yy_get_next_buffer (void );
static void grib_yy_fatal_error (grib_yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up grib_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(grib_yytext_ptr) = grib_yy_bp; \
	grib_yyleng = (size_t) (grib_yy_cp - grib_yy_bp); \
	(grib_yy_hold_char) = *grib_yy_cp; \
	*grib_yy_cp = '\0'; \
	(grib_yy_c_buf_p) = grib_yy_cp;

#define YY_NUM_RULES 105
#define YY_END_OF_BUFFER 106
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct grib_yy_trans_info
	{
	flex_int32_t grib_yy_verify;
	flex_int32_t grib_yy_nxt;
	};
static grib_yyconst flex_int16_t grib_yy_accept[520] =
    {   0,
      102,  102,  106,  104,  102,  103,   12,   93,  101,  104,
      104,  104,   96,    5,  104,    3,   95,   95,   95,   94,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
      104,   18,  102,    6,   14,   97,   99,    0,   98,   96,
        0,    4,    7,    1,    2,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       20,   95,   10,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   15,   95,   95,   95,   95,   95,

       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       16,    0,  100,   98,    0,    0,  100,   95,   21,   95,
       13,   95,   95,   95,    8,   57,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   32,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   11,
       95,   95,   45,   95,   95,   95,   95,   95,   80,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,    0,   99,    0,    0,   98,   95,   95,   95,   95,
       95,   25,   95,   83,   95,   95,   95,   95,   95,   95,

       72,   95,   22,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   58,   95,   95,   27,   95,   95,
       95,   95,   41,   95,   95,   95,   95,   95,   17,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   91,   95,
       95,   95,   95,   95,   95,   95,   82,   95,   95,    0,
       98,   95,   48,   95,   24,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   39,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   26,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   43,
       95,   90,   95,   95,   95,   95,   95,   95,   95,   95,

       95,   95,   95,   95,   28,   88,   95,   89,   68,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   65,   95,
       95,   95,   95,   37,   74,   95,   95,   95,   95,   95,
       67,   95,   40,   95,   95,   61,   95,   95,   95,    9,
       95,   95,   95,   95,   95,   66,   95,   95,   35,   95,
       84,   95,   95,   95,   95,   95,   76,   95,   95,   95,
       86,   95,   95,   79,   85,   95,   59,   95,   95,   95,
       95,   95,   92,   95,   95,   95,   95,   47,   56,   70,
       73,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   31,   49,   95,   95,   95,   95,   95,   51,   95,

       95,   95,   95,   95,   33,   95,   55,   95,   95,   95,
       78,   95,   95,   50,   95,   95,   95,   95,   29,   95,
       23,   95,   36,   95,   95,   95,   95,   95,   95,   95,
       34,   95,   54,   19,   42,   95,   69,   95,   95,   95,
       95,   52,   95,   95,   95,   77,   95,   95,   95,   95,
       95,   95,   95,   81,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   60,   95,   95,   53,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   44,   95,   95,   75,   95,
       87,   95,   95,   95,   95,   95,   95,   95,   95,   95,

       95,   95,   46,   30,   95,   71,   95,   95,   95,   38,
       95,   63,   95,   95,   64,   95,   95,   62,    0
    } ;

static grib_yyconst flex_int32_t grib_yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    7,    8,    1,
        1,    1,    9,    1,    9,   10,    1,   11,   12,   11,
       11,   13,   11,   11,   11,   11,   11,    1,    1,   14,
       15,   16,    1,    1,   17,   17,   17,   17,   18,   17,
       19,   17,   20,   17,   17,   17,   21,   22,   17,   17,
       17,   17,   23,   17,   17,   17,   17,   17,   17,   17,
        1,    1,    1,    1,   24,   25,   26,   27,   28,   29,

       30,   31,   32,   33,   34,   17,   35,   36,   37,   38,
       39,   40,   17,   41,   42,   43,   44,   45,   46,   47,
       48,   17,    1,   49,    1,   50,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static grib_yyconst flex_int32_t grib_yy_meta[51] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    2,    2,    1,    1,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    1,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1
    } ;

static grib_yyconst flex_int16_t grib_yy_base[522] =
    {   0,
        0,    0,  364, 2109,  353, 2109,  339, 2109, 2109,  344,
       40,   43,   48,   47,  312,  310,   56,   59,   62, 2109,
       69,   74,   77,   80,   83,   59,  115,  120,  128,   62,
      123,  112,  135,  164,  152,  113,  155,  158,  191,  195,
      275, 2109,  317, 2109, 2109,  201,  204,  212,  226,  236,
      246, 2109, 2109, 2109, 2109,    0,  229,  239,  252,  256,
      259,  262,  265,  268,  273,  283,  261,  276,  297,  310,
      318,  321,  324,  327,  330,  293,  333,  337,  346,  349,
      357,  360,  369,  373,  378,  382,  385,  388,  393,  399,
      404,  408,  413,  416,  432,  435,  438,  442,  446,  449,

      457,  460,  465,  470,  476,  482,  475,  478,  492,  495,
     2109,  524,  529,  485,  537,  532,  540,  543,  549,  552,
      556,  559,  562,  568,  571,  574,  579,  582,  588,  591,
      599,  602,  611,  614,  620,  623,  634,  630,  637,  640,
      130,  643,  650,  656,  669,  672,  677,  681,  684,  689,
      692,  699,  704,  711,  714,  717,  721,  725,  733,  736,
      739,  746,  756,  759,  765,  768,  771,  777,  783,  789,
      793,  800,  803,  810,  806,  813,  817,  824,  827,  830,
      836,  843,  848,  858,  851,  861,  864,  869,  874,  879,
      882,  885,  888,  891,  894,  897,  905,  908,  914,  917,

      928,  931,  934,  937,  941,  289,  276,  274,  944,  947,
      951,  958,  961,  968,  973,  979,  984,  987,  990,  995,
      999, 1005, 1008, 1011, 1017, 1021, 1024, 1032, 1040, 1043,
     1046, 1050, 1056, 1059, 1062, 1066, 1075, 1078, 1069, 1083,
     1090, 1093, 1098, 1103, 1111, 1114, 1119, 1125, 1130, 1136,
     1139, 1145, 1150, 1153, 1157, 1160, 1163, 1166, 1172, 1175,
     1178, 1183, 1187, 1194, 1197, 1200, 1205,  264,  256,  264,
     1213, 1216, 1224, 1219, 1230, 1233,  261, 1236, 1239, 1249,
     1253, 1256, 1262, 1266, 1269, 1275, 1278, 1284, 1287, 1292,
     1296, 1305, 1312, 1320, 1323, 1326, 1329, 1332, 1335, 1341,

     1344, 1358, 1348, 1364, 1368, 1371, 1374, 1378, 1383, 1386,
     1392, 1395, 1400, 1403, 1409, 1412, 1415, 1418, 1421, 1425,
      258,  245,  239, 1433, 1437, 1440, 1448, 1451, 1458,  214,
     1461, 1464, 1467, 1472, 1477, 1480, 1483, 1488, 1491, 1497,
     1502, 1505, 1508, 1512, 1517, 1521, 1526, 1529, 1532, 1535,
     1545, 1550, 1554, 1557, 1560, 1564, 1567, 1570, 1574, 1577,
     1584, 1592, 1600, 1603, 1606, 1609, 1612,  236,  227,  209,
     1615, 1618, 1625, 1628,  195, 1634, 1637, 1640, 1643, 1648,
     1651, 1654, 1659, 1664, 1669, 1674, 1679, 1682, 1685, 1693,
     1700, 1703, 1706, 1713, 1709, 1718, 1721, 1724, 1728, 1733,

     1739,  206,  200,  191, 1742, 1745, 1748,  182, 1752, 1755,
     1761, 1764, 1767, 1778, 1781, 1784, 1787, 1792, 1795, 1800,
     1803, 1814, 1819, 1822, 1825, 1833, 1837,  178,  191,  182,
     1840,  188, 1846, 1854, 1857, 1860, 1867, 1870, 1873, 1876,
     1879, 1886, 1889, 1892, 1895, 1899, 1902,  157,  172,  182,
      146, 1907, 1911, 1916, 1922, 1925, 1931, 1937, 1942, 1945,
      153,  144,  149,    0, 1948, 1958, 1963, 1966, 1969, 1977,
     1980, 1983,  136,  126,  114, 1988, 1991, 1997, 2000, 2015,
     2018, 2022,  120,  106,  111, 2025, 2031, 2034, 2037, 2044,
     2047, 2050,  101,  105,   91, 2053, 2061, 2064, 2067,   91,

       75,   85, 2070, 2075, 2078, 2081,   85,   81,   63, 2090,
       63,    0,   51,   47,    0,   51,   44,    0, 2109,   63,
       62
    } ;

static grib_yyconst flex_int16_t grib_yy_def[522] =
    {   0,
      519,    1,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  520,  520,  520,  519,
      520,  520,  520,  520,   21,   21,  520,  520,   21,   21,
      520,   31,   31,  520,   31,   31,   31,   31,  520,  520,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  521,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,   21,   21,  520,  520,
      520,  520,  520,  520,  520,  521,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,

      520,  520,  520,  520,  520,  520,   31,   31,   31,   31,
      519,  519,  519,  519,  519,  519,  519,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      521,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  519,  519,  519,  519,  519,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,

      520,  520,  520,  520,  520,  521,  521,  521,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  519,
      519,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  521,  521,  521,
      520,  520,  520,  520,  520,  520,  521,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,

      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      521,  521,  521,  520,  520,  520,  520,  520,  520,  521,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  521,  521,  521,
      520,  520,  520,  520,  521,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,

      520,  521,  521,  521,  520,  520,  520,  521,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  521,  521,  521,
      520,  521,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  521,  521,  521,
      521,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      521,  521,  521,  521,  520,  520,  520,  520,  520,  520,
      520,  520,  521,  521,  521,  520,  520,  520,  520,  520,
      520,  520,  521,  521,  521,  520,  520,  520,  520,  520,
      520,  520,  521,  521,  521,  520,  520,  520,  520,  521,

      521,  521,  520,  520,  520,  520,  521,  521,  521,  520,
      521,  521,  521,  521,  521,  521,  521,  521,    0,  519,
      519
    } ;

static grib_yyconst flex_int16_t grib_yy_nxt[2160] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,    8,   11,   12,
       13,   13,   13,   14,   15,   16,   17,   17,   17,   17,
       18,   17,   17,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   17,   40,   17,   17,   41,   42,
       46,   46,   46,   47,   47,   47,   48,   49,   50,   50,
       50,   52,   53,   56,   57,   51,   56,   56,   56,   56,
       56,   56,   56,   56,   56,  518,  517,   51,   58,   56,
       56,   56,  516,  515,   56,   56,   56,   56,   56,   56,
       56,   56,   56,  514,   75,   59,   57,   57,   57,   57,

       57,   57,   67,   85,   60,  513,   61,   64,   62,   69,
       63,   71,   65,  512,  511,   68,  509,  508,   72,  507,
       73,   66,   57,   70,   57,   56,   76,   56,  502,   74,
       56,   56,   56,   56,   56,   56,  501,   57,   57,  500,
      495,   90,  100,  494,   77,   57,   57,  493,   86,  485,
       91,   57,   87,   78,   79,  484,   88,   80,   81,  483,
       57,   89,  206,   57,   92,   82,  207,   57,   57,   83,
       84,  208,  475,   93,   56,   56,   56,   97,   94,  474,
       57,   57,  473,   57,  101,   57,  464,  106,  102,  103,
       98,   57,   99,   57,  463,  462,   57,  104,  107,  461,

      105,   56,   56,   56,   95,   56,   56,   56,   96,   48,
       49,   46,   46,   46,   47,   47,   47,  451,   51,  450,
      449,  112,  113,  113,  113,  448,  432,  109,  108,  430,
       51,  429,  428,  112,  408,  110,  114,  114,  114,   56,
       56,   56,  404,  115,   48,   49,   50,   50,   50,   56,
       56,   56,  403,   51,  116,  115,  117,  117,  117,  402,
      375,  118,   56,   56,   56,   51,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,  370,  119,   56,   56,   56,  369,  121,  368,  120,
      330,  323,  123,   56,   56,   56,   57,  322,  128,  321,

       57,  122,  129,  270,  130,  269,  124,   56,   56,   56,
      125,   57,  131,  132,  268,  133,  141,   57,   43,  126,
       56,   56,   56,  111,   55,  127,   54,  134,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,  135,   56,   56,   56,
       45,  136,  138,   44,   43,  140,   56,   56,   56,   56,
       56,   56,  137,  519,  519,  143,  139,   56,   56,   56,
       56,   56,   56,  519,  519,  142,  519,  519,  145,   56,
       56,   56,  144,   56,   56,   56,  519,  146,   56,   56,
       56,  519,   56,   56,   56,   56,   56,   56,   56,   56,

       56,  519,  147,   56,   56,   56,  519,  148,  149,   56,
       56,   56,  519,  519,   56,   56,   56,  519,   56,   56,
       56,  519,  150,   56,   56,   56,   56,   56,   56,  151,
      152,  153,  157,  158,  519,  519,  159,  519,  154,  519,
      155,  156,   56,   56,   56,   56,   56,   56,   56,   56,
       56,  161,   56,   56,   56,  160,   56,   56,   56,   56,
       56,   56,  519,  519,  162,  519,  163,   56,   56,   56,
       56,   56,   56,  519,  166,   56,   56,   56,  519,  165,
       56,   56,   56,  164,  168,  167,   56,   56,   56,  519,
      519,  170,   56,   56,   56,  114,  114,  114,  171,  169,

      175,  519,  184,  177,   57,  519,  519,   57,  176,  173,
      172,   57,  519,   57,  184,  519,   57,   57,  174,  178,
       57,  179,  519,  519,   57,  180,  519,  519,  181,  519,
       57,  519,  182,   57,  183,  183,  183,   48,   49,  113,
      113,  113,  117,  117,  117,  185,   51,  186,  186,  186,
      117,  117,  117,   56,   56,   56,  519,  519,   51,   56,
       56,   56,   56,   56,   56,  187,   56,   56,   56,   56,
       56,   56,   56,   56,   56,  519,  519,  188,   56,   56,
       56,   56,   56,   56,   56,   56,   56,  519,  189,   56,
       56,   56,   56,   56,   56,  190,  519,  191,   56,   56,

       56,   56,   56,   56,  519,  193,  519,  519,  192,   56,
       56,   56,   56,   56,   56,  519,  519,  194,  519,  519,
      195,   56,   56,   56,   56,   56,   56,  519,  519,  197,
       56,   56,   56,   56,   56,   56,  519,  519,  196,  200,
       56,   56,   56,  198,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,  519,  519,  199,  201,
       56,   56,   56,  203,  519,  202,   56,   56,   56,  519,
      519,  205,  209,  519,  519,  204,  519,  519,  210,   56,
       56,   56,   56,   56,   56,  519,  211,   56,   56,   56,
      519,   56,   56,   56,   56,   56,   56,  519,  212,   56,

       56,   56,   56,   56,   56,  519,  519,  213,  215,   56,
       56,   56,  519,  216,   56,   56,   56,  214,  519,  519,
      217,   56,   56,   56,   56,   56,   56,   56,   56,   56,
      219,   56,   56,   56,  218,   56,   56,   56,  220,  519,
      221,  519,  223,   56,   56,   56,   56,   56,   56,   56,
       56,   56,  519,  519,  224,  222,   56,   56,   56,  519,
      226,  519,  228,  227,  519,  225,   56,   56,   56,   56,
       56,   56,  519,  519,  229,   56,   56,   56,   56,   56,
       56,   56,   56,   56,  519,  519,  230,   56,   56,   56,
      519,  519,  232,   56,   56,   56,  234,  519,  231,   56,

       56,   56,  233,   56,   56,   56,  237,  519,  519,  235,
       56,   56,   56,   56,   56,   56,   56,   56,   56,  236,
       56,   56,   56,   56,   56,   56,  238,   56,   56,   56,
      519,  519,  239,  240,   56,   56,   56,   56,   56,   56,
       56,   56,   56,  243,  244,  241,   56,   56,   56,  242,
      519,  519,  245,  183,  183,  183,  519,  246,  183,  183,
      183,  186,  186,  186,  247,  248,  250,  519,  251,  251,
      251,  186,  186,  186,   56,   56,   56,  519,  249,   56,
       56,   56,  519,  252,   56,   56,   56,  519,  519,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,

       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
      253,  254,  255,  519,  257,   56,   56,   56,   56,   56,
       56,  519,  256,  519,   56,   56,   56,   56,   56,   56,
      519,  519,  259,  519,  260,  519,  258,  262,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
      261,   56,   56,   56,   56,   56,   56,   56,   56,   56,
      263,   56,   56,   56,  264,  519,  519,  266,   56,   56,
       56,   56,   56,   56,  519,  519,  272,  265,   56,   56,
       56,  271,  267,   56,  277,   56,  273,  519,  274,   56,
       56,   56,  519,  276,   56,   56,   56,   56,   56,   56,

       56,   56,   56,  519,  275,   56,   56,   56,  519,   56,
       56,   56,  519,  280,  278,   56,   56,   56,   56,   56,
       56,   56,   56,   56,  519,  519,  279,   56,   56,   56,
      283,   56,   56,   56,   56,   56,   56,  519,  281,  282,
      519,  284,   56,   56,   56,  519,  285,  519,  519,  287,
       56,   56,   56,   56,   56,   56,   56,   56,   56,  286,
       56,   56,   56,  519,  519,  288,   56,   56,   56,   56,
       56,   56,   56,   56,   56,  519,   56,   56,   56,   56,
       56,   56,  293,  289,  290,   56,   56,   56,   56,   56,
       56,  519,  291,   56,   56,   56,  519,  519,  292,  295,

       56,   56,   56,   56,   56,   56,  294,  297,   56,   56,
       56,  519,  296,   56,   56,   56,  519,  299,  519,  519,
      298,   56,   56,   56,   56,   56,   56,  519,  300,   56,
       56,   56,  519,  519,  302,   56,   56,   56,  519,  301,
       56,   56,   56,  519,  303,  304,  251,  251,  251,  251,
      251,  251,  519,  519,  305,   56,   56,   56,  519,  306,
       56,   56,   56,   56,   56,   56,  307,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,  519,
      519,  308,   56,   56,   56,   56,   56,   56,   56,   56,
       56,  311,  310,   56,   56,   56,  519,   56,   56,   56,

      519,  312,  309,  314,   56,   56,   56,   56,   56,   56,
       56,   56,   56,  519,  313,   56,   56,   56,  315,  519,
      519,  316,  317,   56,   56,   56,   56,   56,   56,   56,
       56,   56,  318,  320,   56,   56,   56,  519,  519,  319,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,  519,  325,  327,  519,  519,  324,  328,   56,
       56,   56,  326,   56,   56,   56,   56,   56,   56,  519,
      519,  331,   56,   56,   56,  329,   56,   56,   56,   56,
       56,   56,  519,  334,  519,   56,   56,   56,   56,   56,
       56,  332,  333,  335,   56,   56,   56,   56,   56,   56,

      519,  519,   56,   56,   56,  519,   56,   56,   56,  519,
      337,  339,  519,  336,  338,   56,   56,   56,  519,  519,
      341,  342,   56,   56,   56,  519,  340,  519,  343,  344,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,  519,  346,
      345,   56,   56,   56,   56,   56,   56,  349,   56,   56,
       56,  347,  519,  350,  348,  519,  352,  351,   56,   56,
       56,  519,  519,  355,   56,   56,   56,  353,   56,   56,
       56,   56,   56,   56,   56,   56,   56,  354,   56,   56,
       56,  519,  357,   56,   56,   56,   56,   56,   56,  519,

      519,  356,   56,   56,   56,   56,   56,   56,  519,  358,
       56,   56,   56,   56,   56,   56,  519,  519,  359,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,  363,   56,   56,   56,  519,  519,
      362,  360,  361,   56,   56,   56,  364,   56,   56,   56,
       56,   56,   56,  519,  519,  366,  519,  365,   56,   56,
       56,   56,   56,   56,  519,  371,  519,  367,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
      373,  519,   56,   56,   56,  519,  372,   56,   56,   56,
       56,   56,   56,   56,   56,   56,  374,  377,   56,   56,

       56,   56,   56,   56,  519,  519,  378,   56,   56,   56,
      519,  376,   56,   56,   56,   56,   56,   56,   56,   56,
       56,  519,   56,   56,   56,  379,  381,   56,   56,   56,
      382,   56,   56,   56,  519,  380,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,  519,  383,
      385,  384,  519,  519,  386,   56,   56,   56,  389,  388,
       56,   56,   56,  387,   56,   56,   56,   56,   56,   56,
       56,   56,   56,  519,   56,   56,   56,   56,   56,   56,
       56,   56,   56,  391,   56,   56,   56,   56,   56,   56,
      519,  519,  390,  394,   56,   56,   56,  392,  519,  519,

      397,  393,   56,   56,   56,  519,  395,  398,  519,  396,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,  519,  401,  400,  399,   56,   56,   56,   56,   56,
       56,  519,  519,  406,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,  519,  405,   56,   56,
       56,   56,   56,   56,   56,   56,   56,  519,  407,   56,
       56,   56,  519,  409,   56,   56,   56,  519,  410,   56,
       56,   56,  519,  411,   56,   56,   56,  519,  412,   56,
       56,   56,   56,   56,   56,   56,   56,   56,  519,  413,

      519,  519,  416,   56,   56,   56,  414,  417,  519,  415,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,  419,   56,   56,   56,  519,  418,   56,   56,
       56,   56,   56,   56,   56,   56,   56,  420,   56,   56,
       56,  421,  422,   56,   56,   56,  519,  423,  424,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,  425,   56,   56,   56,   56,   56,   56,  519,  519,
      426,   56,   56,   56,   56,   56,   56,   56,   56,   56,
      427,  433,  519,  519,  434,  519,  519,  431,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,

      519,  435,   56,   56,   56,   56,   56,   56,  519,  436,
       56,   56,   56,   56,   56,   56,  519,  519,  441,  519,
      439,  519,  519,  438,   56,   56,   56,  519,  437,   56,
       56,   56,   56,   56,   56,   56,   56,   56,  519,  440,
      519,  519,  442,   56,   56,   56,  519,   56,   56,   56,
       56,   56,   56,  519,  519,  443,   56,   56,   56,  519,
      444,  519,  519,  445,   56,   56,   56,   56,   56,   56,
       56,   56,   56,  519,  519,  446,  447,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,  519,  452,  519,  453,   56,   56,   56,   56,

       56,   56,   56,   56,   56,   56,   56,   56,  454,   56,
       56,   56,   56,   56,   56,  455,  456,   56,   56,   56,
      458,   56,   56,   56,  519,  459,   56,   56,   56,  519,
      457,  460,   56,   56,   56,   56,   56,   56,  519,  466,
      519,   56,   56,   56,  519,  519,  465,   56,   56,   56,
      519,  467,   56,   56,   56,   56,   56,   56,   56,   56,
       56,  519,  519,  468,  469,  519,  470,  471,   56,   56,
       56,  519,  472,   56,   56,   56,   56,   56,   56,   56,
       56,   56,  519,  476,  519,  519,  477,   56,   56,   56,
       56,   56,   56,   56,   56,   56,  478,  519,   56,   56,

       56,   56,   56,   56,  519,  519,  479,   56,   56,   56,
       56,   56,   56,  481,  519,  519,  482,  486,  519,  480,
      519,  519,  488,  519,  487,   56,   56,   56,   56,   56,
       56,  489,   56,   56,   56,   56,   56,   56,  519,  519,
      490,   56,   56,   56,   56,   56,   56,   56,   56,   56,
      519,  519,  492,  491,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,  519,  497,  496,  519,
      498,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,  499,  503,   56,   56,   56,   56,   56,
       56,   56,   56,   56,  506,  519,  504,  519,  519,  505,

       56,   56,   56,  519,  519,  519,  519,  510,    3,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519
    } ;

static grib_yyconst flex_int16_t grib_yy_chk[2160] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       11,   11,   11,   12,   12,   12,   13,   13,   13,   13,
       13,   14,   14,  521,  520,   13,   17,   17,   17,   18,
       18,   18,   19,   19,   19,  517,  516,   13,   18,   21,
       21,   21,  514,  513,   22,   22,   22,   23,   23,   23,
       24,   24,   24,  511,   26,   19,   26,   30,   26,   30,

       26,   30,   23,   30,   21,  509,   21,   22,   21,   24,
       21,   25,   22,  508,  507,   23,  502,  501,   25,  500,
       25,   22,   25,   24,   25,   27,   27,   27,  495,   25,
       28,   28,   28,   31,   31,   31,  494,   32,   36,  493,
      485,   32,   36,  484,   27,   32,   36,  483,   31,  475,
       32,   36,   31,   28,   29,  474,   31,   29,   29,  473,
       33,   31,  141,   29,   33,   29,  141,   29,   33,   29,
       29,  141,  463,   33,   34,   34,   34,   35,   33,  462,
       37,   35,  461,   38,   37,   35,  451,   38,   37,   37,
       35,   38,   35,   37,  450,  449,   38,   37,   38,  448,

       37,   39,   39,   39,   34,   40,   40,   40,   34,   46,
       46,   46,   46,   46,   47,   47,   47,  432,   46,  430,
      429,   47,   48,   48,   48,  428,  408,   40,   39,  404,
       46,  403,  402,   47,  375,   40,   49,   49,   49,   57,
       57,   57,  370,   49,   50,   50,   50,   50,   50,   58,
       58,   58,  369,   50,   51,   49,   51,   51,   51,  368,
      330,   58,   59,   59,   59,   50,   60,   60,   60,   61,
       61,   61,   62,   62,   62,   63,   63,   63,   64,   64,
       64,  323,   59,   65,   65,   65,  322,   61,  321,   60,
      277,  270,   63,   66,   66,   66,   67,  269,   67,  268,

       67,   62,   67,  208,   68,  207,   63,   69,   69,   69,
       64,   68,   68,   68,  206,   68,   76,   68,   43,   65,
       70,   70,   70,   41,   16,   66,   15,   69,   71,   71,
       71,   72,   72,   72,   73,   73,   73,   74,   74,   74,
       75,   75,   75,   77,   77,   77,   70,   78,   78,   78,
       10,   71,   73,    7,    5,   75,   79,   79,   79,   80,
       80,   80,   72,    3,    0,   78,   74,   81,   81,   81,
       82,   82,   82,    0,    0,   77,    0,    0,   80,   83,
       83,   83,   79,   84,   84,   84,    0,   82,   85,   85,
       85,    0,   86,   86,   86,   87,   87,   87,   88,   88,

       88,    0,   84,   89,   89,   89,    0,   85,   86,   90,
       90,   90,    0,    0,   91,   91,   91,    0,   92,   92,
       92,    0,   87,   93,   93,   93,   94,   94,   94,   88,
       89,   89,   91,   92,    0,    0,   93,    0,   89,    0,
       90,   90,   95,   95,   95,   96,   96,   96,   97,   97,
       97,   94,   98,   98,   98,   93,   99,   99,   99,  100,
      100,  100,    0,    0,   96,    0,   97,  101,  101,  101,
      102,  102,  102,    0,  100,  103,  103,  103,    0,   99,
      104,  104,  104,   98,  101,  100,  105,  105,  105,    0,
        0,  102,  106,  106,  106,  114,  114,  114,  103,  101,

      107,    0,  114,  108,  107,    0,    0,  108,  107,  105,
      104,  108,    0,  107,  114,    0,  108,  109,  106,  108,
      110,  109,    0,    0,  110,  109,    0,    0,  110,    0,
      109,    0,  112,  110,  112,  112,  112,  113,  113,  113,
      113,  113,  116,  116,  116,  115,  113,  115,  115,  115,
      117,  117,  117,  118,  118,  118,    0,    0,  113,  119,
      119,  119,  120,  120,  120,  118,  121,  121,  121,  122,
      122,  122,  123,  123,  123,    0,    0,  120,  124,  124,
      124,  125,  125,  125,  126,  126,  126,    0,  122,  127,
      127,  127,  128,  128,  128,  123,    0,  124,  129,  129,

      129,  130,  130,  130,    0,  128,    0,    0,  127,  131,
      131,  131,  132,  132,  132,    0,    0,  129,    0,    0,
      130,  133,  133,  133,  134,  134,  134,    0,    0,  132,
      135,  135,  135,  136,  136,  136,    0,    0,  131,  134,
      138,  138,  138,  132,  137,  137,  137,  139,  139,  139,
      140,  140,  140,  142,  142,  142,    0,    0,  133,  135,
      143,  143,  143,  137,    0,  136,  144,  144,  144,    0,
        0,  140,  142,    0,    0,  139,    0,    0,  143,  145,
      145,  145,  146,  146,  146,    0,  144,  147,  147,  147,
        0,  148,  148,  148,  149,  149,  149,    0,  145,  150,

      150,  150,  151,  151,  151,    0,    0,  146,  148,  152,
      152,  152,    0,  149,  153,  153,  153,  147,    0,    0,
      150,  154,  154,  154,  155,  155,  155,  156,  156,  156,
      152,  157,  157,  157,  151,  158,  158,  158,  153,    0,
      154,    0,  156,  159,  159,  159,  160,  160,  160,  161,
      161,  161,    0,    0,  157,  155,  162,  162,  162,    0,
      159,    0,  160,  159,    0,  158,  163,  163,  163,  164,
      164,  164,    0,    0,  161,  165,  165,  165,  166,  166,
      166,  167,  167,  167,    0,    0,  162,  168,  168,  168,
        0,    0,  164,  169,  169,  169,  166,    0,  163,  170,

      170,  170,  165,  171,  171,  171,  169,    0,    0,  167,
      172,  172,  172,  173,  173,  173,  175,  175,  175,  168,
      174,  174,  174,  176,  176,  176,  170,  177,  177,  177,
        0,    0,  171,  172,  178,  178,  178,  179,  179,  179,
      180,  180,  180,  175,  176,  173,  181,  181,  181,  174,
        0,    0,  177,  182,  182,  182,    0,  178,  183,  183,
      183,  185,  185,  185,  179,  180,  184,    0,  184,  184,
      184,  186,  186,  186,  187,  187,  187,    0,  181,  188,
      188,  188,    0,  187,  189,  189,  189,    0,    0,  190,
      190,  190,  191,  191,  191,  192,  192,  192,  193,  193,

      193,  194,  194,  194,  195,  195,  195,  196,  196,  196,
      188,  189,  190,    0,  193,  197,  197,  197,  198,  198,
      198,    0,  191,    0,  199,  199,  199,  200,  200,  200,
        0,    0,  196,    0,  197,    0,  195,  199,  201,  201,
      201,  202,  202,  202,  203,  203,  203,  204,  204,  204,
      198,  205,  205,  205,  209,  209,  209,  210,  210,  210,
      200,  211,  211,  211,  202,    0,    0,  205,  212,  212,
      212,  213,  213,  213,    0,    0,  210,  204,  214,  214,
      214,  209,  205,  215,  215,  215,  211,    0,  212,  216,
      216,  216,    0,  214,  217,  217,  217,  218,  218,  218,

      219,  219,  219,    0,  213,  220,  220,  220,    0,  221,
      221,  221,    0,  219,  216,  222,  222,  222,  223,  223,
      223,  224,  224,  224,    0,    0,  217,  225,  225,  225,
      222,  226,  226,  226,  227,  227,  227,    0,  220,  221,
        0,  224,  228,  228,  228,    0,  225,    0,    0,  227,
      229,  229,  229,  230,  230,  230,  231,  231,  231,  226,
      232,  232,  232,    0,    0,  228,  233,  233,  233,  234,
      234,  234,  235,  235,  235,    0,  236,  236,  236,  239,
      239,  239,  234,  230,  231,  237,  237,  237,  238,  238,
      238,    0,  232,  240,  240,  240,    0,    0,  233,  236,

      241,  241,  241,  242,  242,  242,  235,  238,  243,  243,
      243,    0,  237,  244,  244,  244,    0,  241,    0,    0,
      240,  245,  245,  245,  246,  246,  246,    0,  242,  247,
      247,  247,    0,    0,  244,  248,  248,  248,    0,  243,
      249,  249,  249,    0,  245,  246,  250,  250,  250,  251,
      251,  251,    0,    0,  248,  252,  252,  252,    0,  249,
      253,  253,  253,  254,  254,  254,  252,  255,  255,  255,
      256,  256,  256,  257,  257,  257,  258,  258,  258,    0,
        0,  254,  259,  259,  259,  260,  260,  260,  261,  261,
      261,  258,  257,  262,  262,  262,    0,  263,  263,  263,

        0,  259,  256,  261,  264,  264,  264,  265,  265,  265,
      266,  266,  266,    0,  260,  267,  267,  267,  261,    0,
        0,  262,  263,  271,  271,  271,  272,  272,  272,  274,
      274,  274,  264,  266,  273,  273,  273,    0,    0,  265,
      275,  275,  275,  276,  276,  276,  278,  278,  278,  279,
      279,  279,    0,  272,  274,    0,    0,  271,  275,  280,
      280,  280,  273,  281,  281,  281,  282,  282,  282,    0,
        0,  279,  283,  283,  283,  276,  284,  284,  284,  285,
      285,  285,    0,  282,    0,  286,  286,  286,  287,  287,
      287,  280,  281,  283,  288,  288,  288,  289,  289,  289,

        0,    0,  290,  290,  290,    0,  291,  291,  291,    0,
      285,  287,    0,  284,  286,  292,  292,  292,    0,    0,
      289,  290,  293,  293,  293,    0,  288,    0,  290,  291,
      294,  294,  294,  295,  295,  295,  296,  296,  296,  297,
      297,  297,  298,  298,  298,  299,  299,  299,    0,  294,
      293,  300,  300,  300,  301,  301,  301,  297,  303,  303,
      303,  295,    0,  298,  296,    0,  300,  299,  302,  302,
      302,    0,    0,  303,  304,  304,  304,  301,  305,  305,
      305,  306,  306,  306,  307,  307,  307,  302,  308,  308,
      308,    0,  307,  309,  309,  309,  310,  310,  310,    0,

        0,  304,  311,  311,  311,  312,  312,  312,    0,  310,
      313,  313,  313,  314,  314,  314,    0,    0,  311,  315,
      315,  315,  316,  316,  316,  317,  317,  317,  318,  318,
      318,  319,  319,  319,  315,  320,  320,  320,    0,    0,
      314,  312,  313,  324,  324,  324,  316,  325,  325,  325,
      326,  326,  326,    0,    0,  318,    0,  317,  327,  327,
      327,  328,  328,  328,    0,  326,    0,  320,  329,  329,
      329,  331,  331,  331,  332,  332,  332,  333,  333,  333,
      328,    0,  334,  334,  334,    0,  327,  335,  335,  335,
      336,  336,  336,  337,  337,  337,  329,  334,  338,  338,

      338,  339,  339,  339,    0,    0,  335,  340,  340,  340,
        0,  332,  341,  341,  341,  342,  342,  342,  343,  343,
      343,    0,  344,  344,  344,  337,  339,  345,  345,  345,
      341,  346,  346,  346,    0,  338,  347,  347,  347,  348,
      348,  348,  349,  349,  349,  350,  350,  350,    0,  342,
      344,  343,    0,    0,  345,  351,  351,  351,  350,  348,
      352,  352,  352,  347,  353,  353,  353,  354,  354,  354,
      355,  355,  355,    0,  356,  356,  356,  357,  357,  357,
      358,  358,  358,  353,  359,  359,  359,  360,  360,  360,
        0,    0,  352,  356,  361,  361,  361,  354,    0,    0,

      360,  355,  362,  362,  362,    0,  358,  361,    0,  359,
      363,  363,  363,  364,  364,  364,  365,  365,  365,  366,
      366,  366,  367,  367,  367,  371,  371,  371,  372,  372,
      372,    0,  366,  363,  362,  373,  373,  373,  374,  374,
      374,    0,    0,  372,  376,  376,  376,  377,  377,  377,
      378,  378,  378,  379,  379,  379,    0,  371,  380,  380,
      380,  381,  381,  381,  382,  382,  382,    0,  374,  383,
      383,  383,    0,  376,  384,  384,  384,    0,  377,  385,
      385,  385,    0,  382,  386,  386,  386,    0,  383,  387,
      387,  387,  388,  388,  388,  389,  389,  389,    0,  384,

        0,    0,  387,  390,  390,  390,  385,  388,    0,  386,
      391,  391,  391,  392,  392,  392,  393,  393,  393,  395,
      395,  395,  390,  394,  394,  394,    0,  389,  396,  396,
      396,  397,  397,  397,  398,  398,  398,  391,  399,  399,
      399,  394,  395,  400,  400,  400,    0,  396,  397,  401,
      401,  401,  405,  405,  405,  406,  406,  406,  407,  407,
      407,  398,  409,  409,  409,  410,  410,  410,    0,    0,
      400,  411,  411,  411,  412,  412,  412,  413,  413,  413,
      401,  409,    0,    0,  410,    0,    0,  406,  414,  414,
      414,  415,  415,  415,  416,  416,  416,  417,  417,  417,

        0,  412,  418,  418,  418,  419,  419,  419,    0,  413,
      420,  420,  420,  421,  421,  421,    0,    0,  419,    0,
      417,    0,    0,  416,  422,  422,  422,    0,  415,  423,
      423,  423,  424,  424,  424,  425,  425,  425,    0,  418,
        0,    0,  420,  426,  426,  426,    0,  427,  427,  427,
      431,  431,  431,    0,    0,  422,  433,  433,  433,    0,
      424,    0,    0,  425,  434,  434,  434,  435,  435,  435,
      436,  436,  436,    0,    0,  426,  427,  437,  437,  437,
      438,  438,  438,  439,  439,  439,  440,  440,  440,  441,
      441,  441,    0,  436,    0,  438,  442,  442,  442,  443,

      443,  443,  444,  444,  444,  445,  445,  445,  439,  446,
      446,  446,  447,  447,  447,  440,  441,  452,  452,  452,
      444,  453,  453,  453,    0,  445,  454,  454,  454,    0,
      443,  447,  455,  455,  455,  456,  456,  456,    0,  453,
        0,  457,  457,  457,    0,    0,  452,  458,  458,  458,
        0,  455,  459,  459,  459,  460,  460,  460,  465,  465,
      465,    0,    0,  456,  457,    0,  458,  459,  466,  466,
      466,    0,  460,  467,  467,  467,  468,  468,  468,  469,
      469,  469,    0,  465,    0,    0,  466,  470,  470,  470,
      471,  471,  471,  472,  472,  472,  468,    0,  476,  476,

      476,  477,  477,  477,    0,    0,  469,  478,  478,  478,
      479,  479,  479,  471,    0,    0,  472,  476,    0,  470,
        0,    0,  478,    0,  477,  480,  480,  480,  481,  481,
      481,  479,  482,  482,  482,  486,  486,  486,    0,    0,
      480,  487,  487,  487,  488,  488,  488,  489,  489,  489,
        0,    0,  482,  481,  490,  490,  490,  491,  491,  491,
      492,  492,  492,  496,  496,  496,    0,  488,  487,    0,
      490,  497,  497,  497,  498,  498,  498,  499,  499,  499,
      503,  503,  503,  492,  496,  504,  504,  504,  505,  505,
      505,  506,  506,  506,  499,    0,  497,    0,    0,  498,

      510,  510,  510,    0,    0,    0,    0,  505,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519
    } ;

static grib_yy_state_type grib_yy_last_accepting_state;
static char *grib_yy_last_accepting_cpos;

extern int grib_yy_flex_debug;
int grib_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define grib_yymore() grib_yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *grib_yytext;
#line 1 "gribl.l"
/*
 * Copyright 2005-2014 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 *
 * In applying this licence, ECMWF does not waive the privileges and immunities granted to it by
 * virtue of its status as an intergovernmental organisation nor does it submit to any jurisdiction.
 */
#line 13 "gribl.l"
#include "grib_api_internal.h"
#include "grib_yacc.h"
#include <ctype.h>

int grib_yylineno;

/* Keep -Wall quiet */


/*

This is needed for implementing "include", otherwise
flex buffer optimization break the includes.

*/

#define YY_INPUT(buf,result,max_size) \
        { \
        int c = getc(grib_yyin); \
        result = (c == EOF) ? YY_NULL : (buf[0] = c, 1); \
        }


/*
#ifdef __GNUC__
#ifdef FLEX_SCANNER
void grib_yyunput (int c,char *buf_ptr  );
void _grib_ignore_grib_yyunput_unused_error() { grib_yyunput(0,0); }
#endif
#endif
*/

#line 1137 "lex.grib_yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int grib_yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int grib_yylex_destroy (void );

int grib_yyget_debug (void );

void grib_yyset_debug (int debug_flag  );

YY_EXTRA_TYPE grib_yyget_extra (void );

void grib_yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *grib_yyget_in (void );

void grib_yyset_in  (FILE * in_str  );

FILE *grib_yyget_out (void );

void grib_yyset_out  (FILE * out_str  );

int grib_yyget_leng (void );

char *grib_yyget_text (void );

int grib_yyget_lineno (void );

void grib_yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int grib_yywrap (void );
#else
extern int grib_yywrap (void );
#endif
#endif

    void grib_yyunput (int c,char *buf_ptr  );
    
#ifndef grib_yytext_ptr
static void grib_yy_flex_strncpy (char *,grib_yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int grib_yy_flex_strlen (grib_yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int grib_yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( grib_yytext, grib_yyleng, 1, grib_yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->grib_yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( grib_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( grib_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, grib_yyin))==0 && ferror(grib_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(grib_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "grib_yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef grib_yyterminate
#define grib_yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) grib_yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int grib_yylex (void);

#define YY_DECL int grib_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after grib_yytext and grib_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register grib_yy_state_type grib_yy_current_state;
	register char *grib_yy_cp, *grib_yy_bp;
	register int grib_yy_act;
    
#line 59 "gribl.l"



#line 1323 "lex.grib_yy.c"

	if ( !(grib_yy_init) )
		{
		(grib_yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (grib_yy_start) )
			(grib_yy_start) = 1;	/* first start state */

		if ( ! grib_yyin )
			grib_yyin = stdin;

		if ( ! grib_yyout )
			grib_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			grib_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				grib_yy_create_buffer(grib_yyin,YY_BUF_SIZE );
		}

		grib_yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		grib_yy_cp = (grib_yy_c_buf_p);

		/* Support of grib_yytext. */
		*grib_yy_cp = (grib_yy_hold_char);

		/* grib_yy_bp points to the position in grib_yy_ch_buf of the start of
		 * the current run.
		 */
		grib_yy_bp = grib_yy_cp;

		grib_yy_current_state = (grib_yy_start);
grib_yy_match:
		do
			{
			register YY_CHAR grib_yy_c = grib_yy_ec[YY_SC_TO_UI(*grib_yy_cp)];
			if ( grib_yy_accept[grib_yy_current_state] )
				{
				(grib_yy_last_accepting_state) = grib_yy_current_state;
				(grib_yy_last_accepting_cpos) = grib_yy_cp;
				}
			while ( grib_yy_chk[grib_yy_base[grib_yy_current_state] + grib_yy_c] != grib_yy_current_state )
				{
				grib_yy_current_state = (int) grib_yy_def[grib_yy_current_state];
				if ( grib_yy_current_state >= 520 )
					grib_yy_c = grib_yy_meta[(unsigned int) grib_yy_c];
				}
			grib_yy_current_state = grib_yy_nxt[grib_yy_base[grib_yy_current_state] + (unsigned int) grib_yy_c];
			++grib_yy_cp;
			}
		while ( grib_yy_base[grib_yy_current_state] != 2109 );

grib_yy_find_action:
		grib_yy_act = grib_yy_accept[grib_yy_current_state];
		if ( grib_yy_act == 0 )
			{ /* have to back up */
			grib_yy_cp = (grib_yy_last_accepting_cpos);
			grib_yy_current_state = (grib_yy_last_accepting_state);
			grib_yy_act = grib_yy_accept[grib_yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( grib_yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*grib_yy_cp = (grib_yy_hold_char);
			grib_yy_cp = (grib_yy_last_accepting_cpos);
			grib_yy_current_state = (grib_yy_last_accepting_state);
			goto grib_yy_find_action;

case 1:
YY_RULE_SETUP
#line 62 "gribl.l"
return EQ       ;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 63 "gribl.l"
return GE       ;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 64 "gribl.l"
return GT       ;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 65 "gribl.l"
return LE       ;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 66 "gribl.l"
return LT       ;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 67 "gribl.l"
return NE       ;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 68 "gribl.l"
return NE       ;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 69 "gribl.l"
return BIT      ;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 70 "gribl.l"
return BITOFF   ;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 72 "gribl.l"
return IS   ;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 73 "gribl.l"
return NOT   ;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 74 "gribl.l"
return NOT   ;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 75 "gribl.l"
return AND   ;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 76 "gribl.l"
return AND   ;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 77 "gribl.l"
return OR   ;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "gribl.l"
return OR   ;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 80 "gribl.l"
return NIL   ;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 81 "gribl.l"
return DUMMY   ;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 83 "gribl.l"
return LOWERCASE;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 84 "gribl.l"
return IF       ;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 85 "gribl.l"
return IF_TRANSIENT       ;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 86 "gribl.l"
return ELSE       ;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 87 "gribl.l"
return UNSIGNED ;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 88 "gribl.l"
return ASCII    ;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 89 "gribl.l"
return BYTE    ;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 90 "gribl.l"
return LABEL    ;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 91 "gribl.l"
return LIST     ;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 92 "gribl.l"
return WHILE     ;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 93 "gribl.l"
return TEMPLATE ;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 94 "gribl.l"
return TEMPLATE_NOFAIL ;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 95 "gribl.l"
return TRIGGER ;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 96 "gribl.l"
return END      ;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 97 "gribl.l"
return IBMFLOAT ;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 98 "gribl.l"
return FLOAT ;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 99 "gribl.l"
return SIGNED   ;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 100 "gribl.l"
return CODETABLE;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 101 "gribl.l"
return GETENV;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 102 "gribl.l"
return CODETABLE;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 103 "gribl.l"
return FLAG     ;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 104 "gribl.l"
return LOOKUP   ;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 105 "gribl.l"
return META     ;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 106 "gribl.l"
return PADTOEVEN    ;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 107 "gribl.l"
return PADTO    ;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 108 "gribl.l"
return PADTOMULTIPLE    ;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 109 "gribl.l"
return PAD      ;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 110 "gribl.l"
return SECTION_PADDING      ;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 111 "gribl.l"
return MESSAGE      ;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 112 "gribl.l"
return ALIAS    ;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 113 "gribl.l"
return UNALIAS    ;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 114 "gribl.l"
return POS      ;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 115 "gribl.l"
return INTCONST ;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 116 "gribl.l"
return TRANS    ;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 117 "gribl.l"
return STRING_TYPE   ;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 118 "gribl.l"
return LONG_TYPE   ;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 119 "gribl.l"
return ITERATOR ;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 120 "gribl.l"
return NEAREST ;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 121 "gribl.l"
return BOX ;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 122 "gribl.l"
return KSEC    ;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 123 "gribl.l"
return FLAGBIT    ;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 124 "gribl.l"
return KSEC1EXPVER    ;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 125 "gribl.l"
return MODIFY    ;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 127 "gribl.l"
return G1_HALF_BYTE    ;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 128 "gribl.l"
return G1_MESSAGE_LENGTH    ;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 129 "gribl.l"
return G1_SECTION4_LENGTH    ;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 131 "gribl.l"
return EXPORT;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 132 "gribl.l"
return REMOVE;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 134 "gribl.l"
return SECTION_LENGTH     ;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 136 "gribl.l"
return ASSERT    ;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 138 "gribl.l"
return READ_ONLY;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 139 "gribl.l"
return NO_COPY;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 140 "gribl.l"
return EDITION_SPECIFIC;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 141 "gribl.l"
return DUMP;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 142 "gribl.l"
return NO_FAIL;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 143 "gribl.l"
return HIDDEN;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 144 "gribl.l"
return CAN_BE_MISSING;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 145 "gribl.l"
return MISSING;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 146 "gribl.l"
return CONSTRAINT;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 147 "gribl.l"
return OVERRIDE;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 148 "gribl.l"
return COPY_OK;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 150 "gribl.l"
return SET;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 151 "gribl.l"
return SET_NOFAIL;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 152 "gribl.l"
return WHEN;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 153 "gribl.l"
return CASE;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 154 "gribl.l"
return SWITCH;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 155 "gribl.l"
return DEFAULT;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 156 "gribl.l"
return CONCEPT;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 157 "gribl.l"
return CONCEPT_NOFAIL;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 158 "gribl.l"
return WRITE;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 159 "gribl.l"
return APPEND;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 160 "gribl.l"
return PRINT;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 161 "gribl.l"
return SKIP;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 163 "gribl.l"
{
          int c,q;
          while((c = input()) && isspace(c) && c != '\n') ;
          q = c; /* the quote */

          grib_yyleng = 0;
          while((c = input()) && c != q && c != '\n')
                {
                    if(c == '\\') grib_yytext[grib_yyleng++] = input();
                    else grib_yytext[grib_yyleng++] =  c;
                }

                grib_yytext[grib_yyleng++] = 0;

          grib_parser_include(grib_yytext);
         }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 180 "gribl.l"
{
           int c,q = grib_yytext[0];

           grib_yyleng = 0;

           while((c = input()) && c != q && c != '\n')
           {
               if(c == '\\') grib_yytext[grib_yyleng++] = input();
               else grib_yytext[grib_yyleng++] =  c;
            }

            grib_yytext[grib_yyleng++] = 0;
            grib_yylval.str = strdup(grib_yytext);
            return STRING;
        }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 196 "gribl.l"
{
           int c;
           unsigned long val = 0;

           while((c = input()) && c != '`' && c != '\n')
           {
                val <<= 8;
                val |= c;
           }
           grib_yylval.lval = val;
           return INTEGER;
        }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 210 "gribl.l"
{ grib_yylval.str = strdup(grib_yytext); return IDENT; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 211 "gribl.l"
{ grib_yylval.lval = atol((const char *)grib_yytext); return INTEGER; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 212 "gribl.l"
{ grib_yylval.lval = atol((const char *)grib_yytext); return INTEGER; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 213 "gribl.l"
{ grib_yylval.dval = atof((const char *)grib_yytext); return FLOAT; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 214 "gribl.l"
{ grib_yylval.dval = atof((const char *)grib_yytext); return FLOAT; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 215 "gribl.l"
{ grib_yylval.dval = atof((const char *)grib_yytext); return FLOAT; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 218 "gribl.l"
{
           int c;
           while((c = input()) && (c != '\n')){}

        grib_yylineno++;
        }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 224 "gribl.l"
;
	YY_BREAK
case 103:
/* rule 103 can match eol */
YY_RULE_SETUP
#line 225 "gribl.l"
grib_yylineno++;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 229 "gribl.l"
return *grib_yytext;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 231 "gribl.l"
ECHO;
	YY_BREAK
#line 1977 "lex.grib_yy.c"
case YY_STATE_EOF(INITIAL):
	grib_yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int grib_yy_amount_of_matched_text = (int) (grib_yy_cp - (grib_yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*grib_yy_cp = (grib_yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->grib_yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed grib_yyin at a new source and called
			 * grib_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(grib_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->grib_yy_input_file = grib_yyin;
			YY_CURRENT_BUFFER_LVALUE->grib_yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for grib_yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since grib_yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (grib_yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars)] )
			{ /* This was really a NUL. */
			grib_yy_state_type grib_yy_next_state;

			(grib_yy_c_buf_p) = (grib_yytext_ptr) + grib_yy_amount_of_matched_text;

			grib_yy_current_state = grib_yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * grib_yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			grib_yy_next_state = grib_yy_try_NUL_trans( grib_yy_current_state );

			grib_yy_bp = (grib_yytext_ptr) + YY_MORE_ADJ;

			if ( grib_yy_next_state )
				{
				/* Consume the NUL. */
				grib_yy_cp = ++(grib_yy_c_buf_p);
				grib_yy_current_state = grib_yy_next_state;
				goto grib_yy_match;
				}

			else
				{
				grib_yy_cp = (grib_yy_c_buf_p);
				goto grib_yy_find_action;
				}
			}

		else switch ( grib_yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(grib_yy_did_buffer_switch_on_eof) = 0;

				if ( grib_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * grib_yy_get_next_buffer() to have set up
					 * grib_yytext, we can now set up
					 * grib_yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(grib_yy_c_buf_p) = (grib_yytext_ptr) + YY_MORE_ADJ;

					grib_yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (grib_yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(grib_yy_c_buf_p) =
					(grib_yytext_ptr) + grib_yy_amount_of_matched_text;

				grib_yy_current_state = grib_yy_get_previous_state(  );

				grib_yy_cp = (grib_yy_c_buf_p);
				grib_yy_bp = (grib_yytext_ptr) + YY_MORE_ADJ;
				goto grib_yy_match;

			case EOB_ACT_LAST_MATCH:
				(grib_yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars)];

				grib_yy_current_state = grib_yy_get_previous_state(  );

				grib_yy_cp = (grib_yy_c_buf_p);
				grib_yy_bp = (grib_yytext_ptr) + YY_MORE_ADJ;
				goto grib_yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of grib_yylex */

/* grib_yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int grib_yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf;
	register char *source = (grib_yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (grib_yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->grib_yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (grib_yy_c_buf_p) - (grib_yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((grib_yy_c_buf_p) - (grib_yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->grib_yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars = (grib_yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int grib_yy_c_buf_p_offset =
				(int) ((grib_yy_c_buf_p) - b->grib_yy_ch_buf);

			if ( b->grib_yy_is_our_buffer )
				{
				int new_size = b->grib_yy_buf_size * 2;

				if ( new_size <= 0 )
					b->grib_yy_buf_size += b->grib_yy_buf_size / 8;
				else
					b->grib_yy_buf_size *= 2;

				b->grib_yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					grib_yyrealloc((void *) b->grib_yy_ch_buf,b->grib_yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->grib_yy_ch_buf = 0;

			if ( ! b->grib_yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(grib_yy_c_buf_p) = &b->grib_yy_ch_buf[grib_yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[number_to_move]),
			(grib_yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars = (grib_yy_n_chars);
		}

	if ( (grib_yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			grib_yyrestart(grib_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->grib_yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((grib_yy_size_t) ((grib_yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		grib_yy_size_t new_size = (grib_yy_n_chars) + number_to_move + ((grib_yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf = (char *) grib_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in grib_yy_get_next_buffer()" );
	}

	(grib_yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(grib_yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[0];

	return ret_val;
}

/* grib_yy_get_previous_state - get the state just before the EOB char was reached */

    static grib_yy_state_type grib_yy_get_previous_state (void)
{
	register grib_yy_state_type grib_yy_current_state;
	register char *grib_yy_cp;
    
	grib_yy_current_state = (grib_yy_start);

	for ( grib_yy_cp = (grib_yytext_ptr) + YY_MORE_ADJ; grib_yy_cp < (grib_yy_c_buf_p); ++grib_yy_cp )
		{
		register YY_CHAR grib_yy_c = (*grib_yy_cp ? grib_yy_ec[YY_SC_TO_UI(*grib_yy_cp)] : 1);
		if ( grib_yy_accept[grib_yy_current_state] )
			{
			(grib_yy_last_accepting_state) = grib_yy_current_state;
			(grib_yy_last_accepting_cpos) = grib_yy_cp;
			}
		while ( grib_yy_chk[grib_yy_base[grib_yy_current_state] + grib_yy_c] != grib_yy_current_state )
			{
			grib_yy_current_state = (int) grib_yy_def[grib_yy_current_state];
			if ( grib_yy_current_state >= 520 )
				grib_yy_c = grib_yy_meta[(unsigned int) grib_yy_c];
			}
		grib_yy_current_state = grib_yy_nxt[grib_yy_base[grib_yy_current_state] + (unsigned int) grib_yy_c];
		}

	return grib_yy_current_state;
}

/* grib_yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = grib_yy_try_NUL_trans( current_state );
 */
    static grib_yy_state_type grib_yy_try_NUL_trans  (grib_yy_state_type grib_yy_current_state )
{
	register int grib_yy_is_jam;
    	register char *grib_yy_cp = (grib_yy_c_buf_p);

	register YY_CHAR grib_yy_c = 1;
	if ( grib_yy_accept[grib_yy_current_state] )
		{
		(grib_yy_last_accepting_state) = grib_yy_current_state;
		(grib_yy_last_accepting_cpos) = grib_yy_cp;
		}
	while ( grib_yy_chk[grib_yy_base[grib_yy_current_state] + grib_yy_c] != grib_yy_current_state )
		{
		grib_yy_current_state = (int) grib_yy_def[grib_yy_current_state];
		if ( grib_yy_current_state >= 520 )
			grib_yy_c = grib_yy_meta[(unsigned int) grib_yy_c];
		}
	grib_yy_current_state = grib_yy_nxt[grib_yy_base[grib_yy_current_state] + (unsigned int) grib_yy_c];
	grib_yy_is_jam = (grib_yy_current_state == 519);

	return grib_yy_is_jam ? 0 : grib_yy_current_state;
}

    void grib_yyunput (int c, register char * grib_yy_bp )
{
	register char *grib_yy_cp;
    
    grib_yy_cp = (grib_yy_c_buf_p);

	/* undo effects of setting up grib_yytext */
	*grib_yy_cp = (grib_yy_hold_char);

	if ( grib_yy_cp < YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (grib_yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf )
			*--dest = *--source;

		grib_yy_cp += (int) (dest - source);
		grib_yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars =
			(grib_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_size;

		if ( grib_yy_cp < YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--grib_yy_cp = (char) c;

	(grib_yytext_ptr) = grib_yy_bp;
	(grib_yy_hold_char) = *grib_yy_cp;
	(grib_yy_c_buf_p) = grib_yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int grib_yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(grib_yy_c_buf_p) = (grib_yy_hold_char);

	if ( *(grib_yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* grib_yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (grib_yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars)] )
			/* This was really a NUL. */
			*(grib_yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (grib_yy_c_buf_p) - (grib_yytext_ptr);
			++(grib_yy_c_buf_p);

			switch ( grib_yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because grib_yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					grib_yyrestart(grib_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( grib_yywrap( ) )
						return EOF;

					if ( ! (grib_yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return grib_yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(grib_yy_c_buf_p) = (grib_yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (grib_yy_c_buf_p);	/* cast for 8-bit char's */
	*(grib_yy_c_buf_p) = '\0';	/* preserve grib_yytext */
	(grib_yy_hold_char) = *++(grib_yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void grib_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        grib_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            grib_yy_create_buffer(grib_yyin,YY_BUF_SIZE );
	}

	grib_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	grib_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void grib_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		grib_yypop_buffer_state();
	 *		grib_yypush_buffer_state(new_buffer);
     */
	grib_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(grib_yy_c_buf_p) = (grib_yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_pos = (grib_yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars = (grib_yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	grib_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (grib_yywrap()) processing, but the only time this flag
	 * is looked at is after grib_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(grib_yy_did_buffer_switch_on_eof) = 1;
}

static void grib_yy_load_buffer_state  (void)
{
    	(grib_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars;
	(grib_yytext_ptr) = (grib_yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_pos;
	grib_yyin = YY_CURRENT_BUFFER_LVALUE->grib_yy_input_file;
	(grib_yy_hold_char) = *(grib_yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE grib_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) grib_yyalloc(sizeof( struct grib_yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in grib_yy_create_buffer()" );

	b->grib_yy_buf_size = size;

	/* grib_yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->grib_yy_ch_buf = (char *) grib_yyalloc(b->grib_yy_buf_size + 2  );
	if ( ! b->grib_yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in grib_yy_create_buffer()" );

	b->grib_yy_is_our_buffer = 1;

	grib_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with grib_yy_create_buffer()
 * 
 */
    void grib_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->grib_yy_is_our_buffer )
		grib_yyfree((void *) b->grib_yy_ch_buf  );

	grib_yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a grib_yyrestart() or at EOF.
 */
    static void grib_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	grib_yy_flush_buffer(b );

	b->grib_yy_input_file = file;
	b->grib_yy_fill_buffer = 1;

    /* If b is the current buffer, then grib_yy_init_buffer was _probably_
     * called from grib_yyrestart() or through grib_yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->grib_yy_bs_lineno = 1;
        b->grib_yy_bs_column = 0;
    }

        b->grib_yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void grib_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->grib_yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->grib_yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->grib_yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->grib_yy_buf_pos = &b->grib_yy_ch_buf[0];

	b->grib_yy_at_bol = 1;
	b->grib_yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		grib_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void grib_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	grib_yyensure_buffer_stack();

	/* This block is copied from grib_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(grib_yy_c_buf_p) = (grib_yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_pos = (grib_yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars = (grib_yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(grib_yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from grib_yy_switch_to_buffer. */
	grib_yy_load_buffer_state( );
	(grib_yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void grib_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	grib_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((grib_yy_buffer_stack_top) > 0)
		--(grib_yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		grib_yy_load_buffer_state( );
		(grib_yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void grib_yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(grib_yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(grib_yy_buffer_stack) = (struct grib_yy_buffer_state**)grib_yyalloc
								(num_to_alloc * sizeof(struct grib_yy_buffer_state*)
								);
		if ( ! (grib_yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in grib_yyensure_buffer_stack()" );
								  
		memset((grib_yy_buffer_stack), 0, num_to_alloc * sizeof(struct grib_yy_buffer_state*));
				
		(grib_yy_buffer_stack_max) = num_to_alloc;
		(grib_yy_buffer_stack_top) = 0;
		return;
	}

	if ((grib_yy_buffer_stack_top) >= ((grib_yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (grib_yy_buffer_stack_max) + grow_size;
		(grib_yy_buffer_stack) = (struct grib_yy_buffer_state**)grib_yyrealloc
								((grib_yy_buffer_stack),
								num_to_alloc * sizeof(struct grib_yy_buffer_state*)
								);
		if ( ! (grib_yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in grib_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((grib_yy_buffer_stack) + (grib_yy_buffer_stack_max), 0, grow_size * sizeof(struct grib_yy_buffer_state*));
		(grib_yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE grib_yy_scan_buffer  (char * base, grib_yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) grib_yyalloc(sizeof( struct grib_yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in grib_yy_scan_buffer()" );

	b->grib_yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->grib_yy_buf_pos = b->grib_yy_ch_buf = base;
	b->grib_yy_is_our_buffer = 0;
	b->grib_yy_input_file = 0;
	b->grib_yy_n_chars = b->grib_yy_buf_size;
	b->grib_yy_is_interactive = 0;
	b->grib_yy_at_bol = 1;
	b->grib_yy_fill_buffer = 0;
	b->grib_yy_buffer_status = YY_BUFFER_NEW;

	grib_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to grib_yylex() will
 * scan from a @e copy of @a str.
 * @param grib_yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       grib_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE grib_yy_scan_string (grib_yyconst char * grib_yystr )
{
    
	return grib_yy_scan_bytes(grib_yystr,strlen(grib_yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to grib_yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE grib_yy_scan_bytes  (grib_yyconst char * grib_yybytes, int  _grib_yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	grib_yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _grib_yybytes_len + 2;
	buf = (char *) grib_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in grib_yy_scan_bytes()" );

	for ( i = 0; i < _grib_yybytes_len; ++i )
		buf[i] = grib_yybytes[i];

	buf[_grib_yybytes_len] = buf[_grib_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = grib_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in grib_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->grib_yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void grib_yy_fatal_error (grib_yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine grib_yyless() so it works in section 3 code. */

#undef grib_yyless
#define grib_yyless(n) \
	do \
		{ \
		/* Undo effects of setting up grib_yytext. */ \
        int grib_yyless_macro_arg = (n); \
        YY_LESS_LINENO(grib_yyless_macro_arg);\
		grib_yytext[grib_yyleng] = (grib_yy_hold_char); \
		(grib_yy_c_buf_p) = grib_yytext + grib_yyless_macro_arg; \
		(grib_yy_hold_char) = *(grib_yy_c_buf_p); \
		*(grib_yy_c_buf_p) = '\0'; \
		grib_yyleng = grib_yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int grib_yyget_lineno  (void)
{
        
    return grib_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *grib_yyget_in  (void)
{
        return grib_yyin;
}

/** Get the output stream.
 * 
 */
FILE *grib_yyget_out  (void)
{
        return grib_yyout;
}

/** Get the length of the current token.
 * 
 */
int grib_yyget_leng  (void)
{
        return grib_yyleng;
}

/** Get the current token.
 * 
 */

char *grib_yyget_text  (void)
{
        return grib_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void grib_yyset_lineno (int  line_number )
{
    
    grib_yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see grib_yy_switch_to_buffer
 */
void grib_yyset_in (FILE *  in_str )
{
        grib_yyin = in_str ;
}

void grib_yyset_out (FILE *  out_str )
{
        grib_yyout = out_str ;
}

int grib_yyget_debug  (void)
{
        return grib_yy_flex_debug;
}

void grib_yyset_debug (int  bdebug )
{
        grib_yy_flex_debug = bdebug ;
}

static int grib_yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from grib_yylex_destroy(), so don't allocate here.
     */

    (grib_yy_buffer_stack) = 0;
    (grib_yy_buffer_stack_top) = 0;
    (grib_yy_buffer_stack_max) = 0;
    (grib_yy_c_buf_p) = (char *) 0;
    (grib_yy_init) = 0;
    (grib_yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    grib_yyin = stdin;
    grib_yyout = stdout;
#else
    grib_yyin = (FILE *) 0;
    grib_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * grib_yylex_init()
     */
    return 0;
}

/* grib_yylex_destroy is for both reentrant and non-reentrant scanners. */
int grib_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		grib_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		grib_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	grib_yyfree((grib_yy_buffer_stack) );
	(grib_yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * grib_yylex() is called, initialization will occur. */
    grib_yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef grib_yytext_ptr
static void grib_yy_flex_strncpy (char* s1, grib_yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int grib_yy_flex_strlen (grib_yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *grib_yyalloc (grib_yy_size_t  size )
{
	return (void *) malloc( size );
}

void *grib_yyrealloc  (void * ptr, grib_yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void grib_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see grib_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "grib_yytables"

#line 231 "gribl.l"




