/* newGribRecord.c
** This creates a new Grib Record template which is then filled with the meta-data and filled with the data.
**
** History-
** 	- 2007 09 11:  Created the new file.
*/
#include "ncdcTigge.h"


/* newGribRecord
** 
** returns a new grib record with the meta-data mostly filled out
**
**  Parameters:
**    - int yyyy:	The 4 digit year
**    - int mm:		the 2 digit month
**    - int dd:		the 2 digit day
**    - int hh:		the 2 digit hour (24 hour clock) (of run time)
**    - int fff:	the 3 digit forecast hour
**    - int em:		the 2 digit ensemble member
**
*/
grib_handle* newGribRecord(int yyyy, int mm, int dd, int hh, int fff, int em){
	grib_handle *h = NULL;
	size_t size = 0;
	const void* buffer = NULL;
	
	
	/* Most of this code was generated by the grib_dump tool provided by the grib_api */
	
	/*  The Template "NCEP_GRIB2" was created by Steven Anthony  */
    h = grib_handle_new_from_template(NULL,"GRIB2");
    if(!h) {
        fprintf(stderr,"Cannot create grib handle\n");
        return NULL;
    }
    /* gribSection0 */
    /* 0 = Meteorological products (grib2/0.0.table)  */
    GRIB_CHECK(grib_set_long(h,"discipline",0),0);
    GRIB_CHECK(grib_set_long(h,"editionNumber",2),0);
	
    /* section 1 */
	/* 7 = US National Weather Service - NCEP (WMC) (grib1/0.table)  */
    GRIB_CHECK(grib_set_long(h,"centre",7),0);
    GRIB_CHECK(grib_set_long(h,"subCentre",2),0);

    /* 4 = implemented Nov. 2007, includes the TIGGE definitions (grib2/1.0.table)  */
    GRIB_CHECK(grib_set_long(h,"tablesVersion", 4),0);

    /* 0 = no local table used  (grib2/1.1.table)  */
    GRIB_CHECK(grib_set_long(h,"localTablesVersion", 0),0);

    /* 1 = Start of forecast (grib2/1.2.table)  */
    GRIB_CHECK(grib_set_long(h,"significanceOfReferenceTime",1),0);

    GRIB_CHECK(grib_set_long(h,"year", (long)yyyy),0);
    GRIB_CHECK(grib_set_long(h,"month", (long)mm),0);
    GRIB_CHECK(grib_set_long(h,"day", (long)dd),0);
    GRIB_CHECK(grib_set_long(h,"hour",(long)hh),0);
    GRIB_CHECK(grib_set_long(h,"minute", 0),0);
    GRIB_CHECK(grib_set_long(h,"second", 0),0);

    /* Operational products (grib2/1.3.table)  */
	// TIGGE requires this to be 5 for test, and 4 for Prod.
    GRIB_CHECK(grib_set_long(h,"productionStatusOfProcessedData", 4),0);

    /* 3 = Control forecast products; 4 = peturbed (grib2/1.4.table)  */
	if(em == 0){
    		GRIB_CHECK(grib_set_long(h,"typeOfProcessedData",3),0);
	}else{
		GRIB_CHECK(grib_set_long(h,"typeOfProcessedData",4),0);
	}

    /* 0 = Specified in Code table 3.1 (grib2/3.0.table)  */
    GRIB_CHECK(grib_set_long(h,"sourceOfGridDefinition",0),0);

    //GRIB_CHECK(grib_set_long(h,"numberOfDataPoints",65160),0);
    GRIB_CHECK(grib_set_long(h,"numberOfOctectsForNumberOfPoints",0),0);

    /* 0 = There is no appended list (grib2/3.11.table)  */
    GRIB_CHECK(grib_set_long(h,"interpretationOfNumberOfPoints",0),0);

    /* 0 = Latitude/longitude. Also called equidistant cylindrical, or Plate Carree (grib2/3.1.table)  */
    GRIB_CHECK(grib_set_long(h,"gridDefinitionTemplateNumber",0),0);

    /* Shape of the earth */
    /* 6 = Earth assumed spherical with radius of 6,371,229.0 m (grib2/3.2.table)  */
    GRIB_CHECK(grib_set_long(h,"shapeOfTheEarth",6),0);
    GRIB_CHECK(grib_set_long(h,"scaleFactorOfRadiusOfSphericalEarth",0),0);
    GRIB_CHECK(grib_set_long(h,"scaledValueOfRadiusOfSphericalEarth",0),0);
    GRIB_CHECK(grib_set_long(h,"scaleFactorOfEarthMajorAxis",0),0);
    GRIB_CHECK(grib_set_long(h,"scaledValueOfEarthMajorAxis",0),0);
    GRIB_CHECK(grib_set_long(h,"scaleFactorOfEarthMinorAxis",0),0);
    GRIB_CHECK(grib_set_long(h,"scaledValueOfEarthMinorAxis",0),0);
    
	/* grid information */
    GRIB_CHECK(grib_set_long(h,"Ni",360),0);
    GRIB_CHECK(grib_set_long(h,"Nj",181),0);
    GRIB_CHECK(grib_set_long(h,"basicAngleOfTheInitialProductionDomain",0),0);
    GRIB_CHECK(grib_set_long(h,"subdivisionsOfBasicAngle",0),0);
    GRIB_CHECK(grib_set_long(h,"latitudeOfFirstGridPoint",90000000),0);
    GRIB_CHECK(grib_set_long(h,"longitudeOfFirstGridPoint",0),0);

    /* 48 = 00110000
    (3=1)  i direction increments given
    (4=1)  j direction increments given
    (5=0)  Resolved u- and v- components of vector quantities relative to easterly and northerly directions
    See grib2/3.3.table */
    GRIB_CHECK(grib_set_long(h,"resolutionAndComponentFlags",48),0);
    GRIB_CHECK(grib_set_long(h,"latitudeOfLastGridPoint",-90000000),0);
    GRIB_CHECK(grib_set_long(h,"longitudeOfLastGridPoint",359000000),0);
    GRIB_CHECK(grib_set_long(h,"iDirectionIncrement",1000000),0);
    GRIB_CHECK(grib_set_long(h,"jDirectionIncrement",1000000),0);

    /* 0 = 00000000
    (1=0)  Points of first row or column scan in the +i (+x) direction
    (2=0)  Points of first row or column scan in the -j (-y) direction
    (3=0)  Adjacent points in i (x) direction are consecutive
    (4=0)  All rows scan in the same direction
    See grib2/3.4.table */
    GRIB_CHECK(grib_set_long(h,"scanningMode",0),0);

	/* This is written out for the tigge requirement (missing) */
	GRIB_CHECK(grib_set_missing(h, "subdivisionsOfBasicAngle"), 0);

    /* ITERATOR */
    /* grib 2 Section 4 PRODUCT DEFINITION SECTION */
    GRIB_CHECK(grib_set_long(h,"numberOfCoordinatesValues",0),0);
    /* 1 = Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time  (grib2/4.0.table)  */
    GRIB_CHECK(grib_set_long(h,"productDefinitionTemplateNumber",1),0);

    /* Parameter information */
    /* 0 = Temperature (grib2/4.1.0.table)  */
    //GRIB_CHECK(grib_set_long(h,"parameterCategory",0),0);


    /* 0 = Temperature (K) (grib2/4.2.0.0.table)  */
    //GRIB_CHECK(grib_set_long(h,"parameterNumber",0),0);


    /* 4 = Ensemble forecast (grib2/4.3.table)  */
    GRIB_CHECK(grib_set_long(h,"typeOfGeneratingProcess",4),0);

    GRIB_CHECK(grib_set_long(h,"backgroundProcess",0),0);
    GRIB_CHECK(grib_set_long(h,"generatingProcessIdentifier",80),0);
    GRIB_CHECK(grib_set_long(h,"hoursAfterDataCutoff",0),0);
    GRIB_CHECK(grib_set_long(h,"minutesAfterDataCutoff",0),0);

    /* 1 = Hour (grib2/4.4.table)  */
    GRIB_CHECK(grib_set_long(h,"indicatorOfUnitOfTimeRange",1),0);
	
	// Forecast Time is set to fff
	GRIB_CHECK(grib_set_long(h,"forecastTime", (long)fff ),0);

    /* Horizontal level or layer DEFINE THIS IN YOUR OWN CODE  */
    /* 100 = Isobaric surface (Pa) (grib2/4.5.table)  */
	//  GRIB_CHECK(grib_set_long(h,"typeOfFirstFixedSurface",100),0);
    //  GRIB_CHECK(grib_set_long(h,"scaleFactorOfFirstFixedSurface",0),0);
    //  GRIB_CHECK(grib_set_long(h,"scaledValueOfFirstFixedSurface",97500),0);

    /* 255 = Missing (grib2/4.5.table)  */
    //  GRIB_CHECK(grib_set_long(h,"typeOfSecondFixedSurface",255),0);
    //  GRIB_CHECK(grib_set_long(h,"scaleFactorOfSecondFixedSurface",0),0);
    //  GRIB_CHECK(grib_set_long(h,"scaledValueOfSecondFixedSurface",0),0);

    /* EPS information */
	// This is 1 if it is unperturbed (eg. ensemble member 0)
	// Otherwise, it is 3, which is "positivly perturbed"
	if(em == 0)
		GRIB_CHECK(grib_set_long(h,"typeOfEnsembleForecast",1),0);
	else
		GRIB_CHECK(grib_set_long(h,"typeOfEnsembleForecast",3),0);

	// set the pertubaton Number to the ensemble member number.
    GRIB_CHECK(grib_set_long(h,"perturbationNumber", (long)em),0);
    GRIB_CHECK(grib_set_long(h,"numberOfForecastsInEnsemble", 21),0);

    /* grib 2 Section 5 DATA REPRESENTATION SECTION */
    GRIB_CHECK(grib_set_long(h,"numberOfValues",65160),0);

    /* 40 = JPEG2000 Packing (grib2/5.0.table)  */
    GRIB_CHECK(grib_set_long(h,"dataRepresentationTemplateNumber",40),0);
    //GRIB_CHECK(grib_set_long(h,"decimalScaleFactor",1),0);
    GRIB_CHECK(grib_set_long(h,"bitsPerValue",14),0);

    /* 0 = Floating point (grib2/5.1.table)  */
    GRIB_CHECK(grib_set_long(h,"typeOfOriginalFieldValues",0),0);

    /* 0 = Lossless (grib2/5.40.table)  */
    GRIB_CHECK(grib_set_long(h,"typeOfCompressionUsed",0),0);
    GRIB_CHECK(grib_set_long(h,"targetCompressionRatio",255),0);

	

    /* grib 2 Section 6 BIT-MAP SECTION */
    /* 255 = A bit map does not apply to this product (grib2/6.0.table)  */
    GRIB_CHECK(grib_set_long(h,"bitMapIndicator",255),0);

    /* grib 2 Section 7 data */
/*
    size = 65160;
    v    = (double*)calloc(size,sizeof(double));
    if(!v) {
        fprintf(stderr,"failed to allocate %d bytes\n",size*sizeof(double));
        exit(1);
    }

	for(i=0; i<size; i++){
		v[i] = (double)0.0;
	}

   
    GRIB_CHECK(grib_set_double_array(h,"values",v,size),0);
    free(v);
*/
    /* grib 2 Section 8 END */

/* Save the message */
	
	GRIB_CHECK(grib_get_message(h,&buffer,&size), 0);
	return h;
}


	// Delegator to above, but sets a specific d/c/n/l and zeroes the data section & dates.
grib_handle* newBlankGribRecord( long discipline, long category, long parmNumber, long firstLevelType )
	{
	grib_handle *tmp;
        double* v = NULL;
	int i = 0;
	tmp = newGribRecord( 0,0,0,0,0,0 );

	GRIB_CHECK(grib_set_long( tmp,"discipline", discipline),0);
	GRIB_CHECK(grib_set_long( tmp,"parameterCategory", category),0);
	GRIB_CHECK(grib_set_long( tmp,"parameterNumber", parmNumber), 0);
	GRIB_CHECK(grib_set_long( tmp,"typeOfFirstFixedSurface", firstLevelType ),0);

	size_t size = 65160;
	v = (double*)calloc(size,sizeof(double));
	if(!v) {
		fprintf(stderr,"\n!out of memory err#13461\n" );
		exit(1);
		}

	for( i = 0; i<size; i++) 
		{ v[i] = (double)0.0; }
	GRIB_CHECK( grib_set_double_array( tmp,"values",v,size),0);
	free(v);
	return(tmp);
	}




